### ISSUE TITLE
rewriting parsing the envp into a proper data structure namely a dictionary

### ISSUE THREAD

**Issue by saladuit** [saladuit/minishell#11]
i'm not sure what the previous one exactly did, but it seemed clunky enought to rewrite it

**Comment by Ducorits** [comment]
But should we not simply see if it works or not?
Why rewrite it if we can simply set the project as finished. It's not production code we can just leave it a bit clunky.

**Comment by saladuit** [comment]
This was added by #19 and bug fixes were done in #20 #23 #25
