### ISSUE TITLE
🔧Builtins

### ISSUE THREAD

**Issue by saladuit** [saladuit/minishell#30]
For each function check 

cd:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

pwd:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

env:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

exit:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

echo:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

unset:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

export:
- [ ] Check Sys Calls and add appropriate handle_system_call_error(function_name) function
- [ ] Make compatible with dict
- [ ] Return correct error codes, syscalls are different than builtin erros
- [ ] leaks
- [ ] pre-conditions: such as exit which returns its argument % 256 when it is bigger than 255 && call handle_mini_errors(t_exit_status)

**Comment by saladuit** [comment]
Me: I figured that on a call to exit my program should just call exit, but that was before I knew about _exit() and that was also before I tried to test my program. I'm just not sure how to tackle this problem. A builtin can be called inside of a pipe, but also outside of a pipe. Would you say that the builtin exit call should always call _exit()?

Instead of exiting, what you could do is make your minishell function behave like main; simply return the exit status as an int. When the exit builtin is called, the function returns its exit status.

This makes the function testable, re-enterable, and you can just return the exit status too from the actual main function calling minishell.

**Comment by lucienvb** [comment]
Environment variable keys
1. may only contain underscores, alphabetical characters, or digits. 
2. The first character must either be an underscore or an alphabetical character.
3. The key can't be empty
4. names shall not contain the character '='

Environment variable values:
5. The value cannot contain unquoted dollar signs.

**Comment by saladuit** [comment]
is all handled in separate branches
